# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OutlierAnalysis(object):
    def setupUi(self, OutlierAnalysis):
        OutlierAnalysis.setObjectName("OutlierAnalysis")
        OutlierAnalysis.resize(593, 549)
        self.pages_widget = QtWidgets.QStackedWidget(OutlierAnalysis)
        self.pages_widget.setGeometry(QtCore.QRect(0, 0, 601, 591))
        self.pages_widget.setObjectName("pages_widget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.title_main = QtWidgets.QLabel(self.page_main)
        self.title_main.setGeometry(QtCore.QRect(20, 10, 531, 61))
        self.title_main.setTextFormat(QtCore.Qt.RichText)
        self.title_main.setObjectName("title_main")
        self.description_main = QtWidgets.QLabel(self.page_main)
        self.description_main.setGeometry(QtCore.QRect(20, 50, 301, 51))
        self.description_main.setTextFormat(QtCore.Qt.RichText)
        self.description_main.setObjectName("description_main")
        self.cytof_btn_main = QtWidgets.QPushButton(self.page_main)
        self.cytof_btn_main.setGeometry(QtCore.QRect(20, 190, 559, 62))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cytof_btn_main.sizePolicy().hasHeightForWidth())
        self.cytof_btn_main.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/science.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cytof_btn_main.setIcon(icon)
        self.cytof_btn_main.setObjectName("cytof_btn_main")
        self.rnaseq_btn_main = QtWidgets.QPushButton(self.page_main)
        self.rnaseq_btn_main.setGeometry(QtCore.QRect(20, 280, 559, 62))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rnaseq_btn_main.sizePolicy().hasHeightForWidth())
        self.rnaseq_btn_main.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rnaseq_btn_main.setIcon(icon1)
        self.rnaseq_btn_main.setObjectName("rnaseq_btn_main")
        self.credits_main = QtWidgets.QLabel(self.page_main)
        self.credits_main.setGeometry(QtCore.QRect(20, 493, 301, 51))
        self.credits_main.setTextFormat(QtCore.Qt.RichText)
        self.credits_main.setObjectName("credits_main")
        self.help_main = QtWidgets.QPushButton(self.page_main)
        self.help_main.setGeometry(QtCore.QRect(448, 470, 129, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_main.setIcon(icon2)
        self.help_main.setObjectName("help_main")
        self.quit_main = QtWidgets.QPushButton(self.page_main)
        self.quit_main.setGeometry(QtCore.QRect(448, 506, 129, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/quit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit_main.setIcon(icon3)
        self.quit_main.setObjectName("quit_main")
        self.pages_widget.addWidget(self.page_main)
        self.page_cytof = QtWidgets.QWidget()
        self.page_cytof.setObjectName("page_cytof")
        self.main_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.main_description_cytof.setGeometry(QtCore.QRect(20, 50, 301, 51))
        self.main_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.main_description_cytof.setObjectName("main_description_cytof")
        self.main_title_cytof = QtWidgets.QLabel(self.page_cytof)
        self.main_title_cytof.setGeometry(QtCore.QRect(20, 10, 531, 61))
        self.main_title_cytof.setTextFormat(QtCore.Qt.RichText)
        self.main_title_cytof.setObjectName("main_title_cytof")
        self.input_btn_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.input_btn_cytof.setGeometry(QtCore.QRect(20, 100, 271, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_btn_cytof.sizePolicy().hasHeightForWidth())
        self.input_btn_cytof.setSizePolicy(sizePolicy)
        self.input_btn_cytof.setMinimumSize(QtCore.QSize(0, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_btn_cytof.setIcon(icon4)
        self.input_btn_cytof.setObjectName("input_btn_cytof")
        self.input_echo_cytof = QtWidgets.QLineEdit(self.page_cytof)
        self.input_echo_cytof.setGeometry(QtCore.QRect(20, 130, 551, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_echo_cytof.sizePolicy().hasHeightForWidth())
        self.input_echo_cytof.setSizePolicy(sizePolicy)
        self.input_echo_cytof.setMinimumSize(QtCore.QSize(0, 0))
        self.input_echo_cytof.setText("")
        self.input_echo_cytof.setReadOnly(False)
        self.input_echo_cytof.setObjectName("input_echo_cytof")
        self.analysis_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.analysis_description_cytof.setGeometry(QtCore.QRect(20, 210, 191, 51))
        self.analysis_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.analysis_description_cytof.setObjectName("analysis_description_cytof")
        self.tuckey_15_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.tuckey_15_cytof.setGeometry(QtCore.QRect(230, 280, 58, 23))
        self.tuckey_15_cytof.setChecked(True)
        self.tuckey_15_cytof.setObjectName("tuckey_15_cytof")
        self.TuckeyFactor = QtWidgets.QButtonGroup(OutlierAnalysis)
        self.TuckeyFactor.setObjectName("TuckeyFactor")
        self.TuckeyFactor.addButton(self.tuckey_15_cytof)
        self.tuckey_30_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.tuckey_30_cytof.setGeometry(QtCore.QRect(310, 280, 59, 23))
        self.tuckey_30_cytof.setObjectName("tuckey_30_cytof")
        self.TuckeyFactor.addButton(self.tuckey_30_cytof)
        self.help_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.help_cytof.setGeometry(QtCore.QRect(448, 470, 129, 25))
        self.help_cytof.setIcon(icon2)
        self.help_cytof.setObjectName("help_cytof")
        self.back_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.back_cytof.setGeometry(QtCore.QRect(448, 506, 129, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_cytof.setIcon(icon5)
        self.back_cytof.setObjectName("back_cytof")
        self.run_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.run_cytof.setGeometry(QtCore.QRect(300, 470, 131, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_cytof.sizePolicy().hasHeightForWidth())
        self.run_cytof.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.run_cytof.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/pipe.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_cytof.setIcon(icon6)
        self.run_cytof.setObjectName("run_cytof")
        self.output_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.output_description_cytof.setGeometry(QtCore.QRect(20, 310, 331, 51))
        self.output_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.output_description_cytof.setObjectName("output_description_cytof")
        self.output_text_cytof = QtWidgets.QCheckBox(self.page_cytof)
        self.output_text_cytof.setGeometry(QtCore.QRect(80, 350, 261, 23))
        self.output_text_cytof.setObjectName("output_text_cytof")
        self.output_excel_cytof = QtWidgets.QCheckBox(self.page_cytof)
        self.output_excel_cytof.setEnabled(True)
        self.output_excel_cytof.setGeometry(QtCore.QRect(80, 380, 311, 23))
        self.output_excel_cytof.setObjectName("output_excel_cytof")
        self.output_excel_group_cytof = QtWidgets.QCheckBox(self.page_cytof)
        self.output_excel_group_cytof.setEnabled(False)
        self.output_excel_group_cytof.setGeometry(QtCore.QRect(80, 410, 281, 23))
        self.output_excel_group_cytof.setCheckable(True)
        self.output_excel_group_cytof.setObjectName("output_excel_group_cytof")
        self.tuckey_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.tuckey_description_cytof.setGeometry(QtCore.QRect(117, 265, 121, 51))
        self.tuckey_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.tuckey_description_cytof.setObjectName("tuckey_description_cytof")
        self.outliersby_both_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.outliersby_both_cytof.setGeometry(QtCore.QRect(400, 250, 59, 23))
        self.outliersby_both_cytof.setObjectName("outliersby_both_cytof")
        self.OutliersBy = QtWidgets.QButtonGroup(OutlierAnalysis)
        self.OutliersBy.setObjectName("OutliersBy")
        self.OutliersBy.addButton(self.outliersby_both_cytof)
        self.outliersby_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.outliersby_description_cytof.setGeometry(QtCore.QRect(70, 235, 151, 51))
        self.outliersby_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.outliersby_description_cytof.setObjectName("outliersby_description_cytof")
        self.outliersby_control_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.outliersby_control_cytof.setGeometry(QtCore.QRect(310, 250, 81, 23))
        self.outliersby_control_cytof.setChecked(False)
        self.outliersby_control_cytof.setObjectName("outliersby_control_cytof")
        self.OutliersBy.addButton(self.outliersby_control_cytof)
        self.outliersby_sample_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.outliersby_sample_cytof.setGeometry(QtCore.QRect(230, 250, 81, 23))
        self.outliersby_sample_cytof.setChecked(True)
        self.outliersby_sample_cytof.setObjectName("outliersby_sample_cytof")
        self.OutliersBy.addButton(self.outliersby_sample_cytof)
        self.output_btn_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.output_btn_cytof.setGeometry(QtCore.QRect(20, 160, 271, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_btn_cytof.sizePolicy().hasHeightForWidth())
        self.output_btn_cytof.setSizePolicy(sizePolicy)
        self.output_btn_cytof.setMinimumSize(QtCore.QSize(0, 0))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.output_btn_cytof.setIcon(icon7)
        self.output_btn_cytof.setObjectName("output_btn_cytof")
        self.output_echo_cytof = QtWidgets.QLineEdit(self.page_cytof)
        self.output_echo_cytof.setGeometry(QtCore.QRect(20, 190, 551, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_echo_cytof.sizePolicy().hasHeightForWidth())
        self.output_echo_cytof.setSizePolicy(sizePolicy)
        self.output_echo_cytof.setMinimumSize(QtCore.QSize(0, 0))
        self.output_echo_cytof.setText("")
        self.output_echo_cytof.setReadOnly(False)
        self.output_echo_cytof.setObjectName("output_echo_cytof")
        self.pages_widget.addWidget(self.page_cytof)

        self.retranslateUi(OutlierAnalysis)
        self.pages_widget.setCurrentIndex(1)
        self.output_excel_cytof.clicked['bool'].connect(self.output_excel_group_cytof.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(OutlierAnalysis)

    def retranslateUi(self, OutlierAnalysis):
        _translate = QtCore.QCoreApplication.translate
        OutlierAnalysis.setWindowTitle(_translate("OutlierAnalysis", "Form"))
        self.title_main.setText(_translate("OutlierAnalysis", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Outlier Analysis</span></p></body></html>"))
        self.description_main.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Please choose your desired analysis:</p></body></html>"))
        self.cytof_btn_main.setText(_translate("OutlierAnalysis", " Cytof"))
        self.rnaseq_btn_main.setText(_translate("OutlierAnalysis", " RNAseq"))
        self.credits_main.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Juliano Luiz Faccioni - Labsinal/UFRGS 2018</p></body></html>"))
        self.help_main.setText(_translate("OutlierAnalysis", " Help"))
        self.quit_main.setText(_translate("OutlierAnalysis", " Quit"))
        self.main_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Please choose the settings for the analysis:</p></body></html>"))
        self.main_title_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Outlier Analysis - Cytof data</span></p></body></html>"))
        self.input_btn_cytof.setText(_translate("OutlierAnalysis", " Select input file (.xlsx or .csv) ..."))
        self.analysis_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Select analysis settings:</p></body></html>"))
        self.tuckey_15_cytof.setText(_translate("OutlierAnalysis", "1.&5"))
        self.tuckey_30_cytof.setText(_translate("OutlierAnalysis", "&3.0"))
        self.help_cytof.setText(_translate("OutlierAnalysis", " Help"))
        self.back_cytof.setText(_translate("OutlierAnalysis", " Back"))
        self.run_cytof.setText(_translate("OutlierAnalysis", " Run!"))
        self.output_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Select output settings:</p></body></html>"))
        self.output_text_cytof.setText(_translate("OutlierAnalysis", "Export multiple text files (.csv)"))
        self.output_excel_cytof.setText(_translate("OutlierAnalysis", "Export multiple Excel spreadsheets (.xlsx)"))
        self.output_excel_group_cytof.setText(_translate("OutlierAnalysis", "Group spreadsheets as tabs"))
        self.tuckey_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Tuckey factor:</p></body></html>"))
        self.outliersby_both_cytof.setText(_translate("OutlierAnalysis", "bo&th"))
        self.outliersby_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Generate outliers by:</p></body></html>"))
        self.outliersby_control_cytof.setText(_translate("OutlierAnalysis", "co&ntrol"))
        self.outliersby_sample_cytof.setText(_translate("OutlierAnalysis", "samp&le"))
        self.output_btn_cytof.setText(_translate("OutlierAnalysis", " Select folder to output analysis ..."))

