# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OutlierAnalysis(object):
    def setupUi(self, OutlierAnalysis):
        OutlierAnalysis.setObjectName("OutlierAnalysis")
        OutlierAnalysis.resize(593, 549)
        self.pages_widget = QtWidgets.QStackedWidget(OutlierAnalysis)
        self.pages_widget.setGeometry(QtCore.QRect(0, 0, 601, 591))
        self.pages_widget.setObjectName("pages_widget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.title_main = QtWidgets.QLabel(self.page_main)
        self.title_main.setGeometry(QtCore.QRect(20, 10, 531, 61))
        self.title_main.setTextFormat(QtCore.Qt.RichText)
        self.title_main.setObjectName("title_main")
        self.description_main = QtWidgets.QLabel(self.page_main)
        self.description_main.setGeometry(QtCore.QRect(20, 50, 301, 51))
        self.description_main.setTextFormat(QtCore.Qt.RichText)
        self.description_main.setObjectName("description_main")
        self.cytof_btn_main = QtWidgets.QPushButton(self.page_main)
        self.cytof_btn_main.setGeometry(QtCore.QRect(20, 190, 559, 62))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cytof_btn_main.sizePolicy().hasHeightForWidth())
        self.cytof_btn_main.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/science.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cytof_btn_main.setIcon(icon)
        self.cytof_btn_main.setObjectName("cytof_btn_main")
        self.rnaseq_btn_main = QtWidgets.QPushButton(self.page_main)
        self.rnaseq_btn_main.setGeometry(QtCore.QRect(20, 280, 559, 62))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rnaseq_btn_main.sizePolicy().hasHeightForWidth())
        self.rnaseq_btn_main.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rnaseq_btn_main.setIcon(icon1)
        self.rnaseq_btn_main.setObjectName("rnaseq_btn_main")
        self.credits_main = QtWidgets.QLabel(self.page_main)
        self.credits_main.setGeometry(QtCore.QRect(20, 493, 301, 51))
        self.credits_main.setTextFormat(QtCore.Qt.RichText)
        self.credits_main.setObjectName("credits_main")
        self.help_main = QtWidgets.QPushButton(self.page_main)
        self.help_main.setGeometry(QtCore.QRect(448, 470, 129, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_main.setIcon(icon2)
        self.help_main.setObjectName("help_main")
        self.quit_main = QtWidgets.QPushButton(self.page_main)
        self.quit_main.setGeometry(QtCore.QRect(448, 506, 129, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/quit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit_main.setIcon(icon3)
        self.quit_main.setObjectName("quit_main")
        self.pages_widget.addWidget(self.page_main)
        self.page_cytof = QtWidgets.QWidget()
        self.page_cytof.setObjectName("page_cytof")
        self.main_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.main_description_cytof.setGeometry(QtCore.QRect(20, 50, 301, 51))
        self.main_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.main_description_cytof.setObjectName("main_description_cytof")
        self.main_title_cytof = QtWidgets.QLabel(self.page_cytof)
        self.main_title_cytof.setGeometry(QtCore.QRect(20, 10, 531, 61))
        self.main_title_cytof.setTextFormat(QtCore.Qt.RichText)
        self.main_title_cytof.setObjectName("main_title_cytof")
        self.input_btn_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.input_btn_cytof.setGeometry(QtCore.QRect(20, 100, 271, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_btn_cytof.sizePolicy().hasHeightForWidth())
        self.input_btn_cytof.setSizePolicy(sizePolicy)
        self.input_btn_cytof.setMinimumSize(QtCore.QSize(0, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_btn_cytof.setIcon(icon4)
        self.input_btn_cytof.setObjectName("input_btn_cytof")
        self.input_echo_cytof = QtWidgets.QLineEdit(self.page_cytof)
        self.input_echo_cytof.setGeometry(QtCore.QRect(20, 130, 551, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_echo_cytof.sizePolicy().hasHeightForWidth())
        self.input_echo_cytof.setSizePolicy(sizePolicy)
        self.input_echo_cytof.setMinimumSize(QtCore.QSize(0, 0))
        self.input_echo_cytof.setText("")
        self.input_echo_cytof.setReadOnly(False)
        self.input_echo_cytof.setObjectName("input_echo_cytof")
        self.analysis_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.analysis_description_cytof.setGeometry(QtCore.QRect(20, 250, 191, 51))
        self.analysis_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.analysis_description_cytof.setObjectName("analysis_description_cytof")
        self.tuckey_15_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.tuckey_15_cytof.setGeometry(QtCore.QRect(230, 320, 58, 23))
        self.tuckey_15_cytof.setChecked(True)
        self.tuckey_15_cytof.setObjectName("tuckey_15_cytof")
        self.TuckeyFactor = QtWidgets.QButtonGroup(OutlierAnalysis)
        self.TuckeyFactor.setObjectName("TuckeyFactor")
        self.TuckeyFactor.addButton(self.tuckey_15_cytof)
        self.tuckey_30_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.tuckey_30_cytof.setGeometry(QtCore.QRect(310, 320, 59, 23))
        self.tuckey_30_cytof.setObjectName("tuckey_30_cytof")
        self.TuckeyFactor.addButton(self.tuckey_30_cytof)
        self.help_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.help_cytof.setGeometry(QtCore.QRect(448, 470, 129, 25))
        self.help_cytof.setIcon(icon2)
        self.help_cytof.setObjectName("help_cytof")
        self.back_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.back_cytof.setGeometry(QtCore.QRect(448, 506, 129, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_cytof.setIcon(icon5)
        self.back_cytof.setObjectName("back_cytof")
        self.run_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.run_cytof.setGeometry(QtCore.QRect(300, 470, 131, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_cytof.sizePolicy().hasHeightForWidth())
        self.run_cytof.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.run_cytof.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/pipe.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_cytof.setIcon(icon6)
        self.run_cytof.setObjectName("run_cytof")
        self.output_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.output_description_cytof.setGeometry(QtCore.QRect(20, 340, 331, 51))
        self.output_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.output_description_cytof.setObjectName("output_description_cytof")
        self.output_text_cytof = QtWidgets.QCheckBox(self.page_cytof)
        self.output_text_cytof.setGeometry(QtCore.QRect(80, 380, 261, 23))
        self.output_text_cytof.setObjectName("output_text_cytof")
        self.output_excel_cytof = QtWidgets.QCheckBox(self.page_cytof)
        self.output_excel_cytof.setEnabled(True)
        self.output_excel_cytof.setGeometry(QtCore.QRect(80, 410, 311, 23))
        self.output_excel_cytof.setObjectName("output_excel_cytof")
        self.output_excel_group_cytof = QtWidgets.QCheckBox(self.page_cytof)
        self.output_excel_group_cytof.setEnabled(False)
        self.output_excel_group_cytof.setGeometry(QtCore.QRect(80, 440, 281, 23))
        self.output_excel_group_cytof.setCheckable(True)
        self.output_excel_group_cytof.setObjectName("output_excel_group_cytof")
        self.tuckey_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.tuckey_description_cytof.setGeometry(QtCore.QRect(117, 305, 121, 51))
        self.tuckey_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.tuckey_description_cytof.setObjectName("tuckey_description_cytof")
        self.outliersby_both_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.outliersby_both_cytof.setGeometry(QtCore.QRect(400, 290, 59, 23))
        self.outliersby_both_cytof.setObjectName("outliersby_both_cytof")
        self.OutliersBy = QtWidgets.QButtonGroup(OutlierAnalysis)
        self.OutliersBy.setObjectName("OutliersBy")
        self.OutliersBy.addButton(self.outliersby_both_cytof)
        self.outliersby_description_cytof = QtWidgets.QLabel(self.page_cytof)
        self.outliersby_description_cytof.setGeometry(QtCore.QRect(70, 275, 151, 51))
        self.outliersby_description_cytof.setTextFormat(QtCore.Qt.RichText)
        self.outliersby_description_cytof.setObjectName("outliersby_description_cytof")
        self.outliersby_control_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.outliersby_control_cytof.setGeometry(QtCore.QRect(310, 290, 81, 23))
        self.outliersby_control_cytof.setChecked(False)
        self.outliersby_control_cytof.setObjectName("outliersby_control_cytof")
        self.OutliersBy.addButton(self.outliersby_control_cytof)
        self.outliersby_sample_cytof = QtWidgets.QRadioButton(self.page_cytof)
        self.outliersby_sample_cytof.setGeometry(QtCore.QRect(230, 290, 81, 23))
        self.outliersby_sample_cytof.setChecked(True)
        self.outliersby_sample_cytof.setObjectName("outliersby_sample_cytof")
        self.OutliersBy.addButton(self.outliersby_sample_cytof)
        self.output_btn_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.output_btn_cytof.setGeometry(QtCore.QRect(20, 160, 271, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_btn_cytof.sizePolicy().hasHeightForWidth())
        self.output_btn_cytof.setSizePolicy(sizePolicy)
        self.output_btn_cytof.setMinimumSize(QtCore.QSize(0, 0))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.output_btn_cytof.setIcon(icon7)
        self.output_btn_cytof.setObjectName("output_btn_cytof")
        self.output_echo_cytof = QtWidgets.QLineEdit(self.page_cytof)
        self.output_echo_cytof.setGeometry(QtCore.QRect(20, 190, 551, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_echo_cytof.sizePolicy().hasHeightForWidth())
        self.output_echo_cytof.setSizePolicy(sizePolicy)
        self.output_echo_cytof.setMinimumSize(QtCore.QSize(0, 0))
        self.output_echo_cytof.setText("")
        self.output_echo_cytof.setReadOnly(False)
        self.output_echo_cytof.setObjectName("output_echo_cytof")
        self.samples_btn_cytof = QtWidgets.QPushButton(self.page_cytof)
        self.samples_btn_cytof.setGeometry(QtCore.QRect(20, 230, 271, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samples_btn_cytof.sizePolicy().hasHeightForWidth())
        self.samples_btn_cytof.setSizePolicy(sizePolicy)
        self.samples_btn_cytof.setMinimumSize(QtCore.QSize(0, 0))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.samples_btn_cytof.setIcon(icon8)
        self.samples_btn_cytof.setObjectName("samples_btn_cytof")
        self.pages_widget.addWidget(self.page_cytof)
        self.page_samples = QtWidgets.QWidget()
        self.page_samples.setObjectName("page_samples")
        self.sample_table_samples = QtWidgets.QTableWidget(self.page_samples)
        self.sample_table_samples.setGeometry(QtCore.QRect(20, 160, 561, 291))
        self.sample_table_samples.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sample_table_samples.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sample_table_samples.setObjectName("sample_table_samples")
        self.sample_table_samples.setColumnCount(2)
        self.sample_table_samples.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sample_table_samples.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sample_table_samples.setHorizontalHeaderItem(1, item)
        self.sample_table_samples.horizontalHeader().setDefaultSectionSize(100)
        self.sample_table_samples.horizontalHeader().setMinimumSectionSize(100)
        self.sample_table_samples.horizontalHeader().setStretchLastSection(True)
        self.clear_btn_samples = QtWidgets.QPushButton(self.page_samples)
        self.clear_btn_samples.setGeometry(QtCore.QRect(426, 470, 151, 25))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_btn_samples.setIcon(icon9)
        self.clear_btn_samples.setObjectName("clear_btn_samples")
        self.saveback_btn_samples = QtWidgets.QPushButton(self.page_samples)
        self.saveback_btn_samples.setGeometry(QtCore.QRect(426, 506, 151, 25))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/ok.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveback_btn_samples.setIcon(icon10)
        self.saveback_btn_samples.setObjectName("saveback_btn_samples")
        self.samplename_samples = QtWidgets.QLineEdit(self.page_samples)
        self.samplename_samples.setGeometry(QtCore.QRect(20, 100, 301, 25))
        self.samplename_samples.setObjectName("samplename_samples")
        self.iscontrol_checkbox_samples = QtWidgets.QCheckBox(self.page_samples)
        self.iscontrol_checkbox_samples.setGeometry(QtCore.QRect(20, 130, 141, 23))
        self.iscontrol_checkbox_samples.setObjectName("iscontrol_checkbox_samples")
        self.description_samples = QtWidgets.QLabel(self.page_samples)
        self.description_samples.setGeometry(QtCore.QRect(20, 50, 531, 51))
        self.description_samples.setTextFormat(QtCore.Qt.RichText)
        self.description_samples.setObjectName("description_samples")
        self.title_samples = QtWidgets.QLabel(self.page_samples)
        self.title_samples.setGeometry(QtCore.QRect(20, 10, 531, 61))
        self.title_samples.setTextFormat(QtCore.Qt.RichText)
        self.title_samples.setObjectName("title_samples")
        self.add_btn_samples = QtWidgets.QPushButton(self.page_samples)
        self.add_btn_samples.setGeometry(QtCore.QRect(330, 100, 191, 25))
        self.add_btn_samples.setIcon(icon10)
        self.add_btn_samples.setObjectName("add_btn_samples")
        self.remove_btn_samples = QtWidgets.QPushButton(self.page_samples)
        self.remove_btn_samples.setGeometry(QtCore.QRect(330, 130, 191, 25))
        self.remove_btn_samples.setIcon(icon5)
        self.remove_btn_samples.setObjectName("remove_btn_samples")
        self.pages_widget.addWidget(self.page_samples)

        self.retranslateUi(OutlierAnalysis)
        self.pages_widget.setCurrentIndex(0)
        self.output_excel_cytof.clicked['bool'].connect(self.output_excel_group_cytof.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(OutlierAnalysis)

    def retranslateUi(self, OutlierAnalysis):
        _translate = QtCore.QCoreApplication.translate
        OutlierAnalysis.setWindowTitle(_translate("OutlierAnalysis", "Outlier Analysis"))
        self.title_main.setText(_translate("OutlierAnalysis", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Outlier Analysis</span></p></body></html>"))
        self.description_main.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Please choose your desired analysis:</p></body></html>"))
        self.cytof_btn_main.setText(_translate("OutlierAnalysis", " Cytof"))
        self.rnaseq_btn_main.setText(_translate("OutlierAnalysis", " RNAseq"))
        self.credits_main.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Juliano Luiz Faccioni - Labsinal/UFRGS 2018</p></body></html>"))
        self.help_main.setText(_translate("OutlierAnalysis", " Help"))
        self.quit_main.setText(_translate("OutlierAnalysis", " Quit"))
        self.main_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Please choose the settings for the analysis:</p></body></html>"))
        self.main_title_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Outlier Analysis - Cytof data</span></p></body></html>"))
        self.input_btn_cytof.setText(_translate("OutlierAnalysis", " Select input file (.xlsx or .csv) ..."))
        self.analysis_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Select analysis settings:</p></body></html>"))
        self.tuckey_15_cytof.setText(_translate("OutlierAnalysis", "1.&5"))
        self.tuckey_30_cytof.setText(_translate("OutlierAnalysis", "&3.0"))
        self.help_cytof.setText(_translate("OutlierAnalysis", " Help"))
        self.back_cytof.setText(_translate("OutlierAnalysis", " Back"))
        self.run_cytof.setText(_translate("OutlierAnalysis", " Run!"))
        self.output_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Select output settings:</p></body></html>"))
        self.output_text_cytof.setText(_translate("OutlierAnalysis", "Export multiple text files (.csv)"))
        self.output_excel_cytof.setText(_translate("OutlierAnalysis", "Export multiple Excel spreadsheets (.xlsx)"))
        self.output_excel_group_cytof.setText(_translate("OutlierAnalysis", "Group spreadsheets as tabs"))
        self.tuckey_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Tuckey factor:</p></body></html>"))
        self.outliersby_both_cytof.setText(_translate("OutlierAnalysis", "bo&th"))
        self.outliersby_description_cytof.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Generate outliers by:</p></body></html>"))
        self.outliersby_control_cytof.setText(_translate("OutlierAnalysis", "co&ntrol"))
        self.outliersby_sample_cytof.setText(_translate("OutlierAnalysis", "samp&le"))
        self.output_btn_cytof.setText(_translate("OutlierAnalysis", " Select folder to output analysis ..."))
        self.samples_btn_cytof.setText(_translate("OutlierAnalysis", " Select Sample names ..."))
        item = self.sample_table_samples.horizontalHeaderItem(0)
        item.setText(_translate("OutlierAnalysis", "Control?"))
        item = self.sample_table_samples.horizontalHeaderItem(1)
        item.setText(_translate("OutlierAnalysis", "Label"))
        self.clear_btn_samples.setText(_translate("OutlierAnalysis", " Clear"))
        self.saveback_btn_samples.setText(_translate("OutlierAnalysis", " Save and go back"))
        self.samplename_samples.setPlaceholderText(_translate("OutlierAnalysis", "Insert sample name  ..."))
        self.iscontrol_checkbox_samples.setText(_translate("OutlierAnalysis", "Control Sample?"))
        self.description_samples.setText(_translate("OutlierAnalysis", "<html><head/><body><p>Please insert a sample identifier (e.g. &quot;Control&quot;, &quot;Treatment_01&quot;, &quot;Drug&quot;, ...) :</p></body></html>"))
        self.title_samples.setText(_translate("OutlierAnalysis", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Outlier Analysis - sample names</span></p></body></html>"))
        self.add_btn_samples.setText(_translate("OutlierAnalysis", " Add row"))
        self.remove_btn_samples.setText(_translate("OutlierAnalysis", " Remove selected row"))

